-- |
-- Module      : Crypto.Random.Generator
-- License     : BSD-style
-- Maintainer  : Vincent Hanquez <vincent@snarc.org>
-- Stability   : experimental
-- Portability : Good
--
module Crypto.Random.Generator
    ( CPRG(..)
    ) where

import Data.ByteString (ByteString)
import Crypto.Random.Entropy (EntropyPool, EntropyReseedLevel)

-- | Cryptographic Pseudo Random Generator
class CPRG gen where
    -- | Create a new CPRG using an object of the CryptoGenerator class
    -- and with an explicit reference to an EntropyPool.
    --
    -- The reseed level allow user to specify the reseeding frequency,
    -- during the course of generating bytes.
    --
    -- If EntropyReseed_None is used, then the CPRG should never
    -- be reseeded with entropy bits. this is not recommended except for
    -- debugging and testing purpose.
    cprgCreate :: EntropyPool -> EntropyReseedLevel -> gen

    -- | Split a CPRG into a new independent CPRG.
    --
    -- As entropy is mixed to generate safely a new generator,
    -- 2 calls with the same CPRG will not produce the same output.
    --
    -- If EntropyReseed_None is used, then the generated cprg will be
    -- stricly using the bytes generated from the first generator.
    -- This is not a recommended level except for debugging and testing purpose.
    cprgFork   :: EntropyReseedLevel -> gen -> (gen, gen)

    -- | Generate a number of bytes using the CPRG.
    --
    -- Given one CPRG, the generated bytes will always be the same.
    --
    -- However the returned CPRG might have been reseeded with entropy bits,
    -- so 2 calls with the same CPRG will not necessarily result in the same next CPRG.
    cprgGenerate :: Int -> gen -> (ByteString, gen)
